insert into contacttypes values ('', 'Opener');
insert into contacttypes values ('', 'Buyer');
insert into contacttypes values ('', 'Other');

insert into markets values ('', 'A');
insert into markets values ('', 'B');
insert into markets values ('', 'C');
insert into markets values ('', 'D');

insert into sectors values ('', 'Government', '1');
INSERT INTO `sectors` VALUES (NULL, 'Institutions', '2');
insert into sectors values ('', 'Energy', '10');
insert into sectors values ('', 'Communication', '10');
insert into sectors values ('', 'IT & Electronics', '10');
insert into sectors values ('', 'Transport/Logisitics', '10');
insert into sectors values ('', 'Infrastructure', '10');
insert into sectors values ('', 'Tourism', '10');
insert into sectors values ('', 'Banking & Finance', '10');
insert into sectors values ('', 'Industry', '10');
insert into sectors values ('', 'Media', '10');
insert into sectors values ('', 'Shipping', '10');
insert into sectors values ('', 'Real Estate/Construction', '10');
INSERT INTO `sectors` VALUES (NULL, 'Agriculture', '10');
INSERT INTO `sectors` VALUES (NULL, 'Utilities', '10');
INSERT INTO `sectors` VALUES (NULL, 'Education', '10');
INSERT INTO `sectors` VALUES (NULL, 'Various', '10');
INSERT INTO `sectors` VALUES (NULL, 'Holding', '10');
INSERT INTO `sectors` VALUES (NULL, 'Natural Resources', '10');
INSERT INTO `sectors` VALUES (NULL, 'Defence', '10');
INSERT INTO `sectors` VALUES (NULL, 'Pharmaceuticals', '10');
INSERT INTO `sectors` VALUES (NULL, 'Leisure', '10');
INSERT INTO `sectors` VALUES (NULL, 'Trading', '10');
INSERT INTO `sectors` VALUES (NULL, 'Services', '10');
INSERT INTO `sectors` VALUES (NULL, 'Business', '10');
INSERT INTO `sectors` VALUES (NULL, 'Healthcare', '10');
insert into sectors values ('', 'Other', '1000');
UPDATE `sectors` SET `id` = 0 WHERE `name` = "Other";

insert into statuses values ('', 'Negative');
insert into statuses values ('', 'Unopened');
insert into statuses values ('', 'Open');
insert into statuses values ('', 'Follow-up');
insert into statuses values ('', 'Positive');

insert into media values ('', 'Fortune', 'IPS');
insert into media values ('', 'Newsweek', 'MediaLinks');
insert into media values ('', 'El Mundo', 'BBVision');

insert into project_statuses values ('', 'Open');
insert into project_statuses values ('', 'Closed');

insert into roles values ('', 'Director');
insert into roles values ('', 'Co-director');
insert into roles values ('', 'Coordinator');
insert into roles values ('', 'Journalist');
insert into roles values ('', 'Trainee');
insert into roles values ('', 'PCM');

insert into contact_import_fields values ('', 'Contact.name', 'Contact Name', '');
insert into contact_import_fields values ('', 'Contact.contacttype_id', 'Contact Type', 'Contacttype.name');
insert into contact_import_fields values ('', 'Contact.sector_id', 'Contact Sector', 'Sector.name');
insert into contact_import_fields values ('', 'Contact.market_id', 'Contact Market', 'Market.name');
insert into contact_import_fields values ('', 'Contact.status_id', 'Contact Status', 'Status.name');
insert into contact_import_fields values ('', 'Contact.address', 'Contact Address', '');
insert into contact_import_fields values ('', 'Contact.tel', 'Contact General Tel', '');
insert into contact_import_fields values ('', 'Contact.fax', 'Contact General Fax', '');
insert into contact_import_fields values ('', 'Contact.email', 'Contact General Email', '');
insert into contact_import_fields values ('', 'Contact.website', 'Contact Website', '');
insert into contact_import_fields values ('', 'Note.n.text', 'Contact Note', '');
insert into contact_import_fields values ('', 'Person.0.name', 'Person 1 Name', '');
insert into contact_import_fields values ('', 'Person.0.position', 'Person 1 Position', '');
insert into contact_import_fields values ('', 'Person.0.address', 'Person 1 Address', '');
insert into contact_import_fields values ('', 'Person.0.tel', 'Person 1 Tel', '');
insert into contact_import_fields values ('', 'Person.0.mobile', 'Person 1 Mobile', '');
insert into contact_import_fields values ('', 'Person.0.fax', 'Person 1 Fax', '');
insert into contact_import_fields values ('', 'Person.0.email', 'Person 1 Email', '');
insert into contact_import_fields values ('', 'Person.0.notes', 'Person 1 Note', '');
insert into contact_import_fields values ('', 'Person.1.name', 'Person 2 Name', '');
insert into contact_import_fields values ('', 'Person.1.position', 'Person 2 Position', '');
insert into contact_import_fields values ('', 'Person.1.address', 'Person 2 Address', '');
insert into contact_import_fields values ('', 'Person.1.tel', 'Person 2 Tel', '');
insert into contact_import_fields values ('', 'Person.1.mobile', 'Person 2 Mobile', '');
insert into contact_import_fields values ('', 'Person.1.fax', 'Person 2 Fax', '');
insert into contact_import_fields values ('', 'Person.1.email', 'Person 2 Email', '');
insert into contact_import_fields values ('', 'Person.1.notes', 'Person 2 Note', '');
insert into contact_import_fields values ('', 'Person.2.name', 'Person 3 Name', '');
insert into contact_import_fields values ('', 'Person.2.position', 'Person 3 Position', '');
insert into contact_import_fields values ('', 'Person.2.address', 'Person 3 Address', '');
insert into contact_import_fields values ('', 'Person.2.tel', 'Person 3 Tel', '');
insert into contact_import_fields values ('', 'Person.2.mobile', 'Person 3 Mobile', '');
insert into contact_import_fields values ('', 'Person.2.fax', 'Person 3 Fax', '');
insert into contact_import_fields values ('', 'Person.2.email', 'Person 3 Email', '');
insert into contact_import_fields values ('', 'Person.2.notes', 'Person 3 Note', '');
insert into contact_import_fields values ('', 'Note.n.text', 'Other (Add as note)', '');
insert into contact_import_fields values ('', '', '*Ignore this column*', '');
